# Generated by Django 5.0.7 on 2024-07-16 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavemindTranlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_language', models.CharField(choices=[('ESP', 'Español'), ('ENG', 'Engles')], default='ESP', max_length=5)),
                ('to_language', models.CharField(choices=[('ESP', 'Español'), ('ENG', 'Engles')], default='ENG', max_length=5)),
                ('word', models.CharField(max_length=100)),
                ('translated_Word', models.CharField(max_length=100)),
                ('context_word_use', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
