# Generated by Django 5.0.7 on 2024-07-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemindtranlate',
            name='from_language',
            field=models.CharField(choices=[('ESP', 'Español'), ('ENG', 'Ingles')], default='ESP', max_length=5),
        ),
        migrations.AlterField(
            model_name='savemindtranlate',
            name='to_language',
            field=models.CharField(choices=[('ESP', 'Español'), ('ENG', 'Ingles')], default='ENG', max_length=5),
        ),
    ]
