# Generated by Django 5.0.7 on 2024-07-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_savemindtranlate_from_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemindtranlate',
            name='context_word_use',
            field=models.TextField(blank=True),
        ),
    ]
