# Generated by Django 5.0.7 on 2024-07-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_savemindtranlate_context_word_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemindtranlate',
            name='translated_Word',
            field=models.CharField(max_length=250),
        ),
    ]
