# Generated by Django 5.0.7 on 2024-07-18 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_savemindtranlate_translated_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemindtranlate',
            name='to_language',
            field=models.CharField(choices=[('ESP', 'Español'), ('ENG', 'Ingles')], default='ENG', max_length=10),
        ),
    ]
