# Generated by Django 5.0.7 on 2024-07-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_savemindtranlate_to_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savemindtranlate',
            name='from_language',
            field=models.CharField(default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='savemindtranlate',
            name='to_language',
            field=models.CharField(default='es', max_length=5),
        ),
    ]
